### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by RusseII** [porter-finance/product#10]
https://github.com/porter-finance/product/blob/main/vision.md
> - Will allow us to gain adoption for treasury

Can you clarify what that means?

**Comment by jordanalexandermeyer** [comment]
Thanks for asking, this was extremely poorly worded.

I was trying to communicate that we will be able to release a treasury solution in the future that will allow liens to be placed on the treasury. This will allow debt holders first rights to treasury assets in the case of a default, making them senior to equity holders in terms of liabilities.

I've updated it here: https://github.com/porter-finance/product/pull/11/files#diff-bb9e42012dbeff17af98ec12ee25449f4b0358b9a28037e7c8ea891b99b44ed3
