### ISSUE TITLE
create_auction_page questions

### ISSUE THREAD

**Issue by RusseII** [porter-finance/product#12]
A few questions on the [create_auction_page bond_config](https://github.com/porter-finance/product/blob/main/spec/pages/create_auction_page/features/bond_config.md)

1.
 >Bond asset contract address

Why is this an input? I thought the new bond contract would be deployed upon the conclusion of a successful auction? 

2.
> Max interest rate

So they would add the max interest rate here, then we would use that number to calculate the bond minimum sell price for the auction?

**Comment by jordanalexandermeyer** [comment]
> > Bond asset contract address
> Why is this an input? I thought the new bond contract would be deployed upon the conclusion of a successful auction?
This label is confusing. I'm referring to the asset being borrowed. I'll add descriptions to each of these to clarify.
 
> > Max interest rate
> So they would add the max interest rate here, then we would use that number to calculate the bond minimum sell price for the auction?
Yes.
