### ISSUE TITLE
Auction Management questions 

### ISSUE THREAD

**Issue by RusseII** [porter-finance/product#13]
https://github.com/porter-finance/product/blob/main/spec/pages/auction_page/features/auction_management.md

Are there more auction management features we will need for v1? Like adding/removing addresses from allow-list after the auction has already started

**Comment by jordanalexandermeyer** [comment]
Yes, I need to add "adding addresses from allow-list". Removing an address may lead to problems (removing an address that has already submitted a bid) so let's hold off on that one. Thanks for pointing this out!
