### ISSUE TITLE
Debt Auction Question

### ISSUE THREAD

**Issue by RusseII** [porter-finance/product#15]
What's the use case for having an `upcoming` period for a debt auction vs starting it right away after being initiated? 

From what I can tell - Gnosis's auction is [immediately started](https://github.com/gnosis/ido-contracts/blob/e7a363591e3f0a8735f90a9f04f5062351559d7d/contracts/EasyAuction.sol#L152) after being initialized without any `upcoming` period

**Comment by jordanalexandermeyer** [comment]
Great question! The upcoming period allows DAOs to advertise their bond auction and increase awareness. Users can navigate to the auction page and and become familiar with the platform before the auction starts.

**Comment by RusseII** [comment]
> I'd argue it's a better user experience than only being able to discover an auction once it has already started.

@jordanalexandermeyer I could see it either way. If it was a dutch auction we would need it for sure, but from my understanding timing doesn't really matter for a batch auction - so might be better user experience for users if they can bid right away vs having an artificial waiting period. 

Im ok with having it or not having it - but would recommend taking a step back and reconsidering if it adds value to our protocol or if it's just bloat.

**Comment by jordanalexandermeyer** [comment]
I agree on the dutch auction vs batch auction front. If it adds lift, I think we should cut the upcoming period.

**Comment by RusseII** [comment]
> I agree on the dutch auction vs batch auction front. If it adds lift, I think we should cut the upcoming period.

It'd be product complexity, not technical lift. It shouldn't be difficult to build from the technical side but from product side it's another auction `state` that DAOs and investors need to understand and be aware of. It also adds another variable that DAOs would need to decide on when initiating a debt auction.

**Comment by jordanalexandermeyer** [comment]
Scheduling the auction increases the amount of time an auction is displayed on the site. This makes it more likely a user who is browsing the site will have something to engage with. In addition, it gives the auction starter a chance to cancel the auction before it starts if they realize something is wrong after reviewing the auction page.

If it's not a large technical lift, I think we should keep the 'upcoming' state.

**Comment by RusseII** [comment]
>Scheduling the auction increases the amount of time an auction is displayed on the site. This makes it more likely a user who is browsing the site will have something to engage with. 

They could also just increase the duration of the auction right?

>  it gives the auction starter a chance to cancel the auction before it starts

This is valid - we could handle this use case in another way if we wanted though - for example we could allow them to cancel up for up to 6 hours after starting the auction and return any sell bids to investors

**Comment by jordanalexandermeyer** [comment]
I think it would be a bad user experience to pay the high gas fees and send a substantial amount of money for a bid and then have the auction be cancelled. The user would then have to notice it was cancelled and pay more gas to retrieve their funds. Once the auction has been started, there should be no going back.

**Comment by RusseII** [comment]
> It would be a bad user experience to pay the high gas fees and send a substantial amount of money for a bid and then have the auction be cancelled. The user would then have to notice it was cancelled and pay more gas to retrieve their funds. 

Sure but there are ways to work around this. For example - we could charge a fee for the DAO to cancel the auction and use this money to compensate the bidders. 

I'm pretty sure we could design it in a way where the `cancelAuction` transaction would automatically return funds to the bidders (and the auctioneer would pay the gas) 

We are going to need to enable some sort of similar functionality anyway since investors need a way to get their funds if their bids were lower than the clearing price - or if the auction fails to meet the auction requirements

**Comment by jordanalexandermeyer** [comment]
1. As an investor, if I see an auction is live and I can bid on it, I would not expect it to be cancellable by the auctioneer. 
2. If I'm bidding on a bond auction, I have spent significant time and resources on my side underwriting the bond issuer, deciding the interest rate I want, and potentially getting investor buy in from my partners. To have the auction cancelled after I have put forth so much effort would force me to question whether the whole process is worth it.
3.
> I'm pretty sure we could design it in a way where the cancelAuction transaction would automatically return funds to the > bidders (and the auctioneer would pay the gas)
> 
> We are going to need to enable some sort of similar functionality anyway since investors need a way to get their funds if > their bids were lower than the clearing price - or if the auction fails to meet the auction requirements
Yes, but in the case where the auction ran to completion and a bid is not filled, the auctioneer should not be responsible for paying the gas to return the funds. The bidder should pay the gas to claim their funds because they did not make a competitive offer. 

Therefore, we would have to implement two different ways to return funds to the investors. One which would return all the funds to bidders in the event of a cancellation and one where bidders would claim unfilled bid funds.
