### ISSUE TITLE
Do we need a user flow around the vetting process?

### ISSUE THREAD

**Issue by RusseII** [porter-finance/product#17]
Are we planning on having vetted auctions upon our initial release? 

If so: 
* How will auctions get vetted? 
* What's the user flow of the vetter?

**Comment by jordanalexandermeyer** [comment]
Great question. There are a couple of options we can pursue so I will make a discussion document. I want to consider integrating with https://www.prime.xyz/rating. Having a rating for the technicals, fundamentals, as well as the financials would be huge.
