### ISSUE TITLE
Add docs.porter.finance to discord

### ISSUE THREAD

**Issue by RusseII** [porter-finance/product#25]
<img width="625" alt="image" src="https://user-images.githubusercontent.com/15036618/154853071-f115fbb7-30ad-4d6d-b79e-017da84d8e9d.png">
https://canary.discord.com/channels/903094151002857492/903802976106324018/903804344552525824

Add docs.porter.finance to intro on discord

**Comment by jordanalexandermeyer** [comment]
Done
