### ISSUE TITLE
combine `product discovery page` and `portfolio page` ?

### ISSUE THREAD

**Issue by RusseII** [porter-finance/product#32]
Should `product discovery page` and `portfolio page` be combined? 

I'm working on [writing out the data](https://github.com/porter-finance/v1-core/issues/77#issuecomment-1066948729) that needs queried for each of the pages outlined in [pages](https://github.com/porter-finance/product/tree/main/spec/pages) and portfolio page seems to be the product discovery page with a filter of `bondholder===user.address`

**Comment by jordanalexandermeyer** [comment]
Great callout. I will have to think about how this changes the view of the product discover page (may want to separate user bonds from rest of list or something), **but let's combine the two pages**.

**Comment by jordanalexandermeyer** [comment]
We decided not to merge these because the portfolio page may be used for more functions in the future.
