### ISSUE TITLE
Bond page feedback

### ISSUE THREAD

**Issue by RusseII** [porter-finance/product#45]
<img width="1157" alt="image" src="https://user-images.githubusercontent.com/15036618/162002678-c9ad38e0-e6f6-4ed5-b450-39f66580d2a9.png">

https://github.com/porter-finance/product/tree/main/spec/pages/product_page/simple

This page feels like it's missing a lot of info I would want to know as a bondholder. 

* How much are my bonds worth?
* How much collateral is backing my bonds and what's the collateral ratio in dollar terms?
* Does supply matter? 
* *Collateral Tokens* subtext should be collateral per bond? 

I'm using the linked figma NEW - https://github.com/porter-finance/frontend-ido/issues/36 is that up to date? There seems to be a lot of incorrect namings

**Comment by jordanalexandermeyer** [comment]
Great points @RusseII!

I've added the following:
* Estimated value
* Face value
* Collateral ratio

I removed "supply" and "put strike price".
